UI/Controllers/AgencyController.cs
using Common;
using System;
using System.Text;
using System.Web.Mvc;
using UI.Factories;

namespace UI.Controllers
{
    public class AgencyController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var vm = AgencyCategoryVMFactory.GetAgencyVM();
            return View("Classifires", vm);
        }

        [HttpGet]
        public ActionResult Sets(Guid id, int rating = 0)
        {
            var vm = AgencyCategoryVMFactory.GetAgencySetsVM(id, rating);
            return View(vm);
        }

        [HttpGet]
        [AjaxRequest]
        public JsonResult Load(Guid id, int page = 1, int rating = 0)
        {
            var data = AgencyCategoryVMFactory.LoadAgencySets(id, page, rating);
            return Json(data, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/Controllers/SetController.cs
using Common;
using Repository.Entities;
using Repository.Misc;
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using UI.Factories;
using UI.Models;

namespace UI.Controllers
{
    public class SetController : Controller
    {
        [HttpGet]
        public ActionResult View(Guid? setVer = null, string passportId = null, string versId = null, string structId = null)
        {
            var categorySet = setVer.HasValue && setVer.Value != Guid.Empty;
            var agencySet = !string.IsNullOrWhiteSpace(passportId);

            if (!(categorySet ^ agencySet)) return new HttpNotFoundResult();


            // no need to store filters data if we just load this page or reload it
            Session.Clear();

            var userIP = Request.UserHostAddress;

            SetViewVM vm;

            if (categorySet)
                vm = SetVMFactory.CreateSetViewVM(setVer.Value, userIP);
            else
                vm = SetVMFactory.CreateSetViewVM(passportId, versId, structId, userIP);

            return View(vm);
        }

        [HttpGet]
        public JsonResult LoadTemplate(Guid templId)
        {
            var vm = SetVMFactory.LoadTemplate(templId);
            return Json(vm, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult LoadStructure(Guid structId)
        {
            var vm = SetVMFactory.LoadStructure(structId);
            return Json(vm, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult LoadData(Guid verId, Guid structId, string passportId = null, int page = 1,
            Guid? fullViewItemId = null, Guid? parentItemId = null)
        {
            // fullViewItemId == null && parentItemId == null means what we load simple table data
            // fullViewItemId != null && parentItemId == null means what we load fullview item
            // fullViewItemId == null && parentItemId != null means what we load additional set items of fullview item
            string filterQuery = (string)Session[structId.ToString()];

            var vm = SetVMFactory.LoadData(verId, structId, passportId, page, filterQuery, fullViewItemId, parentItemId);
            return Json(vm, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AjaxRequest]
        public JsonResult LoadElementsCount(Guid verId, Guid structId, string passportId = null)
        {
            string filterQuery = (string)Session[structId.ToString()];

            try
            {
                int result = SetVMFactory.LoadElementsCount(verId, structId, passportId, filterQuery);
                return Json(new { count = result, itemsPerPage = Configuration.Base.ItemsPerPage }, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { IsOk = false, reason = e }, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
            }


        }

        [HttpPost]
        [AjaxRequest]
        public void ProcessFilterQuery(string structId)
        {
            // TODO: Compleate
            StringBuilder filterQuery = new StringBuilder();
            int keysCount = Request.Form.AllKeys.Count(x => x.Contains("_type"));
            foreach (var key in Request.Form.AllKeys.Where(x => x.Contains("_type")))
            {
                keysCount--;
                var type = Request.Form[key];
                var field = key.Replace("_type", "");
                var val = Request.Form[field];

                if (string.IsNullOrWhiteSpace(val)) continue;

                int type_val = -1;
                if (int.TryParse(type, out type_val) && type_val > -1)
                {
                    var _type = (ColumnDisplayTemplate.ContentType)type_val;
                    var queryItem = _type.CreateSqlQueryFilterItem(field, val);
                    if (!string.IsNullOrWhiteSpace(queryItem))
                    {
                        if (keysCount > 0)
                            filterQuery.AppendFormat("{0} AND ", queryItem);
                        else
                            filterQuery.Append(queryItem);
                    }
                }
            }

            var query = filterQuery.ToString();
            if (query.EndsWith("AND ", StringComparison.InvariantCultureIgnoreCase))
                query = query.Remove(query.Length - 4);


            if (string.IsNullOrWhiteSpace(query))
                Session.Remove(structId);
            else
                Session[structId] = query;
        }

        [HttpPost]
        [AjaxRequest]
        public JsonResult SetRating(string id, string structId, string versId, int value)
        {
            var userIP = Request.UserHostAddress;
            var vm = SetVMFactory.SetRating(id, structId, versId, value, userIP);
            return Json(vm, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/Controllers/StatusController.cs
using System.Web.Mvc;
using UI.Factories;
using UI.Models;

namespace UI.Controllers
{
    public class StatusController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            StatusVM vm = StatusVMFactory.GetIndexVM();
            return View("Status", vm);
        }
    }
}

UI/Views/Status/Status.cshtml
@model UI.Models.StatusVM

@{
    ViewBag.Title = Model.Title;
}

@Scripts.Render("~/scripts/plugins/tabs")
@Styles.Render("~/styles/jquery-ui")

<div class="content">
    <div>
        @Html.Partial("~/Views/Partial/Selector/Topbar.cshtml", Model.TopbarVM)
    </div>
    <div class="b-tabs ui-tabs ui-widget ui-widget-content ui-corner-all">
        <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" role="tablist">
            <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab" tabindex="0" aria-controls="tabs-added" aria-labelledby="ui-id-1" aria-selected="true" aria-expanded="true">
                <a id="ui-id-1" class="ui-tabs-anchor" href="#tabs-added" role="presentation" tabindex="-1">Добавленные</a>
            </li>
            <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="tabs-updated" aria-labelledby="ui-id-2" aria-selected="false" aria-expanded="false">
                <a id="ui-id-2" class="ui-tabs-anchor" href="#tabs-updated" role="presentation" tabindex="-1">Обновленные</a>
            </li>
        </ul>

        <div id="tabs-added" class="ui-tabs-panel ui-widget-content ui-corner-bottom" aria-labelledby="ui-id-1" role="tabpanel" aria-hidden="false">
            <div class="data_table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Дата создания</th>
                            <th>Наименование</th>
                            <th>Описание</th>
                            <th>Категория</th>
                            <th>Поставщик</th>
                            <th>Актуален до</th>
                        </tr>
                    </thead>
                    <tbody id="table_added">
                        @if (Model.AddedItems.Count() == 0)
                        {
                            <tr>
                                <td colspan="7">Данные отсутствуют</td>
                            </tr>
                        }
                        else
                        {
                            int i = 1;
                            foreach (var item in Model.AddedItems)
                            {
                            <tr>
                                <td>@i</td>
                                <td>@item.CreationDate.ToShortDateString()</td>
                                <td>@Html.ActionLink(item.Name, "View", "Set", new { setVer = item.Id }, new { title = "Просмотреть данные всех поставщиков" })</td>
                                <td>@item.Description</td>
                                <td>@item.Category</td>
                                <td>
                                    <ul>
                                        @foreach (var agency in item.Agencies)
                                        {
                                            <li>
                                                @Html.ActionLink(agency.Name, "Sets", "Agency", new { id = agency.AgencyId }, null);
                                            </li>
                                        }
                                    </ul>
                                </td>
                                <td></td>
                            </tr>
                                        ++i;
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div id="tabs-updated" class="ui-tabs-panel ui-widget-content ui-corner-bottom" aria-labelledby="ui-id-2" role="tabpanel" style="display: none;" aria-hidden="true">
            <div class="data_table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Дата последнего изменения</th>
                            <th>Наименование</th>
                            <th>Описание</th>
                            <th>Категория</th>
                            <th>Поставщик</th>
                            <th>Актуален до</th>
                        </tr>
                    </thead>
                    <tbody id="table_modified">
                        @if (Model.ModifiedItems.Count() == 0)
                        {
                            <tr>
                                <td colspan="7">Данные отсутствуют</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(function () {
        $('.b-tabs').tabs();
    });
</script>