UI/Controllers/FileController.cs
using Repository.Misc;
using System;
using System.IO;
using System.Net;
using System.Web.Mvc;
using UI.Factories;

namespace UI.Controllers
{
    public class FileController : Controller
    {
        [HttpGet]
        public ActionResult List(string format)
        {
            Formats _format;
            string mimeType;
            string fname;

            switch (format)
            {
                case ".xml":
                case "xml":
                    _format = Formats.xml;
                    mimeType = "text/xml";
                    fname = "list.xml";
                    break;
                case "-schema.xsd":
                    _format = Formats.xsd;
                    mimeType = "text/xsd";
                    fname = "list-schema.xsd";
                    break;
                case ".csv":
                case "csv":
                    _format = Formats.csv;
                    mimeType = "text/csv";
                    fname = "list.csv";
                    break;
                default:
                    return new HttpNotFoundResult();
            }

            string url_prefix = string.Format("{0}://{1}/opendata", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority);
            byte[] fileStream = FileVMFactory.GetList(url_prefix, _format, Server.MapPath);

            return File(fileStream, mimeType, fname);
        }


        [HttpGet]
        public ActionResult Meta(string setId, string version = null, string format = "xml")
        {
            Formats _format;
            string mimeType;
            string fname;


            switch (format)
            {
                case ".xml":
                case "xml":
                    _format = Formats.xml;
                    mimeType = "text/xml";
                    fname = "meta.xml";
                    break;
                case "-schema.xsd":
                    _format = Formats.xsd;
                    mimeType = "text/xsd";
                    fname = "meta-schema.xsd";
                    break;
                case ".csv":
                case "csv":
                    _format = Formats.csv;
                    mimeType = "text/csv";
                    fname = "meta.csv";
                    break;
                default:
                    return new HttpNotFoundResult();
            }

            string url_prefix = string.Format("{0}://{1}/opendata", HttpContext.Request.Url.Scheme, HttpContext.Request.Url.Authority);
            byte[] fileStream = FileVMFactory.GetMeta(setId, version, url_prefix, _format, Server.MapPath);

            if (fileStream == null || fileStream.Length == 0)
                return new HttpNotFoundResult();

            return File(fileStream, mimeType, fname);
        }


        [HttpGet]
        public ActionResult Data(string setId, string versId, string structId, string format = "xml")
        {
            Formats _format;
            string mimeType;
            string fname;


            switch (format)
            {
                case "xml":
                case ".xml":
                    _format = Formats.xml;
                    mimeType = "text/xml";
                    fname = string.Format("data-{0}-structure-{1}.xml", versId, structId);
                    break;
                case "-schema.xsd": case ".xsd":
                    return Structure(setId, structId, format);
                case "csv":
                case ".csv":
                    _format = Formats.csv;
                    mimeType = "text/csv";
                    fname = string.Format("data-{0}-structure-{1}.csv", versId, structId);
                    break;
                default:
                    return new HttpNotFoundResult();
            }


            byte[] fileStream = FileVMFactory.GetData(setId, versId, structId, _format, Server.MapPath);
            return File(fileStream, mimeType, fname);
        }

        [HttpGet]
        public ActionResult Structure(string setId, string structId, string format = "xml")
        {
            Formats _format;
            string mimeType;
            string fname;


            switch (format)
            {
                case "xml":
                case ".xml":
                    _format = Formats.xml;
                    mimeType = "text/xml";
                    fname = string.Format("structure-{0}.xml", structId);
                    break;
                case "xsd":
                case ".xsd":
                    _format = Formats.xml;
                    mimeType = "text/xsd";
                    fname = string.Format("structure-{0}.xsd", structId);
                    break;
                case "csv":
                case ".csv":
                    _format = Formats.csv;
                    mimeType = "text/csv";
                    fname = string.Format("structure-{0}.csv", structId);
                    break;
                default:
                    return new HttpNotFoundResult();
            }


            byte[] fileStream = FileVMFactory.GetStructure(setId, structId, _format, Server.MapPath);
            return File(fileStream, mimeType, fname);
        }

        [HttpGet]
        public ActionResult SetVersionStructure(Guid setVerId, string format)
        {
            Formats _format;
            string mimeType;
            string fname;


            switch (format)
            {
                case "xml":
                case ".xml":
                    _format = Formats.xml;
                    mimeType = "text/xml";
                    fname = "structure.xml";
                    break;
                case "xsd":
                case ".xsd":
                    _format = Formats.xml;
                    mimeType = "text/xsd";
                    fname = "structure.xsd";
                    break;
                case "csv":
                case ".csv":
                    _format = Formats.csv;
                    mimeType = "text/csv";
                    fname = "structure.csv";
                    break;
                default:
                    return new HttpNotFoundResult();
            }


            byte[] fileStream = FileVMFactory.GetStructure(setVerId, _format, Server.MapPath);
            return File(fileStream, mimeType, fname);
        }

        [HttpGet]
        public ActionResult SetVersionData(Guid setVerId, string format)
        {
            Formats _format;
            string mimeType;
            string fname;


            switch (format)
            {
                case "xml":
                case ".xml":
                    _format = Formats.xml;
                    mimeType = "text/xml";
                    fname = "data.xml";
                    break;
                case "-schema.xsd":
                case ".xsd":
                    return SetVersionStructure(setVerId, format);
                case "csv":
                case ".csv":
                    _format = Formats.csv;
                    mimeType = "text/csv";
                    fname = "data";
                    break;
                default:
                    return new HttpNotFoundResult();
            }


            byte[] fileStream = FileVMFactory.GetData(setVerId, _format, Server.MapPath);
            return File(fileStream, mimeType, fname);
        }
    }
}

UI/Controllers/SetController.cs
using Common;
using Repository.Entities;
using Repository.Misc;
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using UI.Factories;
using UI.Models;

namespace UI.Controllers
{
    public class SetController : Controller
    {
        [HttpGet]
        public ActionResult View(Guid? setVer = null, string passportId = null, string versId = null, string structId = null)
        {
            var categorySet = setVer.HasValue && setVer.Value != Guid.Empty;
            var agencySet = !string.IsNullOrWhiteSpace(passportId);

            if (!(categorySet ^ agencySet)) return new HttpNotFoundResult();


            // no need to store filters data if we just load this page or reload it
            Session.Clear();

            var userIP = Request.UserHostAddress;

            SetViewVM vm;

            if (categorySet)
                vm = SetVMFactory.CreateSetViewVM(setVer.Value, userIP);
            else
                vm = SetVMFactory.CreateSetViewVM(passportId, versId, structId, userIP);

            return View(vm);
        }

        [HttpGet]
        public JsonResult LoadTemplate(Guid templId)
        {
            var vm = SetVMFactory.LoadTemplate(templId);
            return Json(vm, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult LoadStructure(Guid structId)
        {
            var vm = SetVMFactory.LoadStructure(structId);
            return Json(vm, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult LoadData(Guid verId, Guid structId, string passportId = null, int page = 1,
            Guid? fullViewItemId = null, Guid? parentItemId = null)
        {
            // fullViewItemId == null && parentItemId == null means what we load simple table data
            // fullViewItemId != null && parentItemId == null means what we load fullview item
            // fullViewItemId == null && parentItemId != null means what we load additional set items of fullview item
            string filterQuery = (string)Session[structId.ToString()];

            var vm = SetVMFactory.LoadData(verId, structId, passportId, page, filterQuery, fullViewItemId, parentItemId);
            return Json(vm, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AjaxRequest]
        public JsonResult LoadElementsCount(Guid verId, Guid structId, string passportId = null)
        {
            string filterQuery = (string)Session[structId.ToString()];

            try
            {
                int result = SetVMFactory.LoadElementsCount(verId, structId, passportId, filterQuery);
                return Json(new { count = result, itemsPerPage = Configuration.Base.ItemsPerPage }, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { IsOk = false, reason = e }, "text/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
            }


        }

        [HttpPost]
        [AjaxRequest]
        public void ProcessFilterQuery(string structId)
        {
            // TODO: Compleate
            StringBuilder filterQuery = new StringBuilder();
            int keysCount = Request.Form.AllKeys.Count(x => x.Contains("_type"));
            foreach (var key in Request.Form.AllKeys.Where(x => x.Contains("_type")))
            {
                keysCount--;
                var type = Request.Form[key];
                var field = key.Replace("_type", "");
                var val = Request.Form[field];

                if (string.IsNullOrWhiteSpace(val)) continue;

                int type_val = -1;
                if (int.TryParse(type, out type_val) && type_val > -1)
                {
                    var _type = (ColumnDisplayTemplate.ContentType)type_val;
                    var queryItem = _type.CreateSqlQueryFilterItem(field, val);
                    if (!string.IsNullOrWhiteSpace(queryItem))
                    {
                        if (keysCount > 0)
                            filterQuery.AppendFormat("{0} AND ", queryItem);
                        else
                            filterQuery.Append(queryItem);
                    }
                }
            }

            var query = filterQuery.ToString();
            if (query.EndsWith("AND ", StringComparison.InvariantCultureIgnoreCase))
                query = query.Remove(query.Length - 4);


            if (string.IsNullOrWhiteSpace(query))
                Session.Remove(structId);
            else
                Session[structId] = query;
        }

        [HttpPost]
        [AjaxRequest]
        public JsonResult SetRating(string id, string structId, string versId, int value)
        {
            var userIP = Request.UserHostAddress;
            var vm = SetVMFactory.SetRating(id, structId, versId, value, userIP);
            return Json(vm, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/Views/Partial/DownloadButton.cshtml
@model UI.Models.DownloadButtonVM

@{
    bool isAgency = Model.Id is string;

    Func<string, string> structUrl = null;
    Func<string, string> metaUrl = null;
    Func<string, string> dataUrl = null;

    if (!isAgency)
    {
        structUrl = x => Url.Action("SetVersionStructure", "File", new { setVerId = Model.Id, format = x });
        dataUrl = x => Url.Action("SetVersionData", "File", new { setVerId = Model.Id, format = x });
    }
    else
    {
        metaUrl = x => Url.Action("Meta", "File", new { setId = Model.Id, format = x });
        structUrl = x => Url.Action("Structure", "File", new { setId = Model.Id, structId = Model.StructId, format = x });
        dataUrl = x => Url.Action("Data", "File", new { setId = Model.Id, versId = Model.VersionId, structId = Model.StructId, format = x });
    }
}

<div class="js-dropdown dropdown dropdown--right">
    <div class="dropdown__current">
        <a href="@dataUrl("xml")" class="download min_button"><span></span></a>
    </div>

    <div class="dropdown__sub">
        <div class="dropdown__sub__inner">
            <div class="b-docs-list">
                <ul>
                    @if ((Model.AvaliableButtons & UI.Models.DownloadButtonVM.Buttons.Meta) == UI.Models.DownloadButtonVM.Buttons.Meta)
                    {
                        
                        @*<li class="xml">
                            <a href="@metaUrl("xml")">СКАЧАТЬ ПАСПОРТ НАБОРА</a>
                            <span class="size">(XML)</span>
                        </li>
                        
                        <li class="json">
                            <a href="@metaUrl("json")">СКАЧАТЬ ПАСПОРТ НАБОРА</a>
                            <span class="size">(JSON)</span>
                        </li>*@
                                
                        <li class="csv">
                            <a href="@metaUrl("csv")">СКАЧАТЬ ПАСПОРТ НАБОРА</a>
                            <span class="size">(CSV)</span>
                        </li>
                                
                        <hr />
                    }

                    @if ((Model.AvaliableButtons & UI.Models.DownloadButtonVM.Buttons.Structure) == UI.Models.DownloadButtonVM.Buttons.Structure)
                    {
                             
                        @*<li class="xml">
                            <a href="@structUrl("xml")">СКАЧАТЬ ПАСПОРТ СТРУКТУРЫ НАБОРА</a>
                            <span class="size">(XML)</span>
                        </li>
                                
                        <li class="json">
                            <a href="@structUrl("json")">СКАЧАТЬ ПАСПОРТ СТРУКТУРЫ НАБОРА</a>
                            <span class="size">(JSON)</span>
                        </li>*@
                        <li class="csv">
                            <a href="@structUrl("csv")">СКАЧАТЬ ПАСПОРТ СТРУКТУРЫ НАБОРА</a>
                            <span class="size">(CSV)</span>
                        </li>

                        <hr />
                    }
                    @if ((Model.AvaliableButtons & UI.Models.DownloadButtonVM.Buttons.Data) == UI.Models.DownloadButtonVM.Buttons.Data)
                    {   
                        @*<li class="xml">
                            <a href="@dataUrl("xml")">СКАЧАТЬ НАБОР</a>
                            <span class="size">(XML)</span>
                        </li>
                                
                        <li class="json">
                            <a href="@dataUrl("json")">СКАЧАТЬ НАБОР</a>
                            <span class="size">(JSON)</span>
                        </li>*@
                                
                        <li class="csv">
                            <a href="@dataUrl("csv")">СКАЧАТЬ НАБОР</a>
                            <span class="size">(CSV)</span>
                        </li>
                    }
                    @*<span class="count">Cкачали: @Model.Downloaded</span>*@
                </ul>
            </div>
        </div>
    </div>
</div>

UI/Views/Partial/Map.cshtml
<link rel="stylesheet" href="http://openlayers.org/en/v3.17.1/css/ol.css" type="text/css">


<script src="http://openlayers.org/en/v3.17.1/build/ol.js" type="text/javascript"></script>
<div id="map" class="map" style="width:100%; height:600px;"></div>
<script type="text/javascript">

    var markers = [];
    $(function () {

        $('#tabs-map').show();

        var map = new ol.Map({
            target: 'map',
            layers: [
              new ol.layer.Tile({
                  source: new ol.source.OSM()
              })
            ],
            view: new ol.View({
                center: ol.proj.fromLonLat([38.8759731, 45.0537048]),
                zoom: 11
            })
        });

        $(window).trigger("resize");

        //$('#tabs-map').hide();

        setTimeout(map.updateSize(), 100);

        
    });
</script>

UI/Views/Partial/Pager.cshtml
<nav class="pager"></nav>

UI/Views/Partial/Set.cshtml
@model UI.Models.SetViewVM.SetViewParams

@{
    Guid dummy;
    bool isCategoryView = Guid.TryParse(Model.Id.ToString(), out dummy);
}

<div class="set__line set__table long-table-wrapper" id="setContent">
</div>

<script type="text/javascript" src="~/Scripts/app/tableGenerator.js"></script>

<script type="text/javascript">

    var currentDataStructId = '@Model.DataStructureId';
    var setId = '@Model.Id.ToString()';

    $(function () {

        var tableGenerator;

        $.getJSON('@Url.Action("LoadStructure", "Set")',
            { structId: currentDataStructId })
            .success(function (res) {
                tableGenerator = new TableGenerator(res,
                    '@Model.VersionId',
                    @if (isCategoryView)
                    {
                        @:null
                    }
                    else
                    {
                        @:'@Model.Id'
                    }
                    , '@Url.Action("LoadData", "Set")',
                    '@Url.Action("LoadTemplate", "Set")',
                    '@Url.Action("LoadElementsCount", "Set")',
                    '@Url.Action("ProcessFilterQuery", "Set")',
                    markers);

                tableGenerator.Generate($('#setContent'));
            });
    });
</script>


UI/Views/Partial/SetPassports.cshtml
@model IEnumerable<UI.Models.SetPassportVM>

@{
    bool isMultitable = Model.Count() > 0;
}

@{
}

<div class="set-passorts-list">
    <div class="b-tabs b-tabs-vertical">

        <ul>
            @{ int i = 1;
               foreach (var passport in Model)
               {
                <li>
                    <a href="#tab-@i">
                        <span>@passport.Creator</span>
                    </a>
                </li>
                   i++;
               }
               i = 1;
            }
        </ul>


        @foreach (var passport in Model)
        {
            <div id="tab-@i">
                <table class="passport_table">
                    <tbody>

                        <tr>
                            <th colspan="2">Версия методических рекомендаций</th>
                            <td>@passport.MethodicStandartVersion
                                <span>
                                    @{ 
                                        var vm = new UI.Models.DownloadButtonVM
                                        {
                                            AvaliableButtons = UI.Models.DownloadButtonVM.Buttons.Meta,
                                            Id = passport.Identifier,
                                            StructId = passport.StructCodeName,
                                            VersionId = passport.VersCodeName
                                        };
                                        Html.RenderPartial("~/Views/Partial/DownloadButton.cshtml", vm);
                                    }
                                </span>
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <th colspan="2">Идентефикационный номер набора</th>
                            <td>@passport.Identifier</td>
                        </tr>
                        <tr>
                            <th colspan="2">Наименование набора данных</th>
                            <td><a href="~/@passport.Identifier/data-@passport.VersCodeName-structure-@passport.StructCodeName">@passport.Title</a></td>
                        </tr>
                        <tr>
                            <th colspan="2">Описание набора данных</th>
                            <td>@passport.Description</td>
                        </tr>
                        <tr>
                            <th colspan="2">Владелец набора данных</th>
                            <td>@passport.Creator</td>
                        </tr>

                        <tr>
                            <th rowspan="4">Ответственное лицо</th>
                        </tr>
                        <tr>
                            <th>Ф. И. О.</th>
                            <td>@passport.PublisherName</td>
                        </tr>
                        <tr>
                            <th>Телефон</th>
                            <td>@Html.DisplayFor(x => passport.PublisherPhone)</td>
                        </tr>
                        <tr>
                            <th>E-Mail</th>
                            <td>@Html.DisplayFor(x => passport.PublisherMBox)</td>
                        </tr>

                        <tr>
                            <th colspan="2">Дата первой публикации набора</th>
                            <td>@Html.DisplayFor(x => passport.Created)</td>
                        </tr>
                        <tr>
                            <th colspan="2">Дата последнего внесения изменений</th>
                            <td>@Html.DisplayFor(x => passport.Modified)</td>
                        </tr>
                        <tr>
                            <th colspan="2">Ключевые слова, соответствующие содержанию набора</th>
                            <td>@passport.Subject</td>
                        </tr>
                        <tr>
                            <th colspan="2">Актуален до</th>
                            <td>@Html.DisplayFor(x => passport.Valid)</td>
                        </tr>

                    </tbody>
                </table>
            </div>
            i++;
        }
    </div>


    @if (i > 2)
    {
        <div class="spl__note">
            Примечание: 
              Для набора может присутствовать несколько паспортов в виду того, что для данного набора предоставляют данные несколько поставщиков
        </div>
    }
</div>
<!-- /set passports list -->

UI/Views/Partial/SetVersionsInfo.cshtml
@model UI.Models.SetVersionsInfoVM


@{
    bool isAgency = Model.Id is string;
}

<script type="text/javascript" src="~/Scripts/plugins/jstree/jstree.js"></script>

<script type="text/javascript">
    $(function () {
        
        $("#jstree").jstree();

        

        $('span', $('#jstree')).on("changed.jstree", function (e, data) {
            alert($(this).html());
        });
    });
</script>


<link rel="stylesheet" href="~/Content/Stylesheets/plugins/jstree/default/style.css" />



@helper CreateVersionNode(UI.Models.SetVersionsInfoVM item, bool isAgency)
{
    <li data-jstree='{ "selected" : @item.IsCurrent.ToString().ToLowerInvariant() }'>

        <span>
            @if (isAgency)
            {
                <a href="@string.Format("/{0}/data-{1}-structure-{2}", item.Id, item.VersId, item.StructId)">@string.Format("{0} ({1:dd.MM.yyyy})", item.Name, item.CreationDate)</a>
            }   
            else
            {
                <a href="@string.Format("/{0}",item.Id)">@string.Format("{0} ({1:dd.MM.yyyy})", item.Name, item.CreationDate)</a>
            }
        </span>

        @if (item.SubVersions.Any())
        {
            <ul>
                @foreach (var subVersion in item.SubVersions)
                {
                    @CreateVersionNode(subVersion, isAgency);
                }
            </ul>
        }
    </li>
}



<div class="set-versions-list">
    <div id="jstree">
        <ul>
            @CreateVersionNode(Model, isAgency)
        </ul>
    </div>
</div>